
- type: http
  urls: ["http://in.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://1.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://2.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://3.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://4.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://5.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://6.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://7.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://8.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://9.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://10.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://11.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://12.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://13.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://14.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://15.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://16.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://17.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://18.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://19.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://20.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://21.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://22.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://23.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://24.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://25.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://26.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://27.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://28.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://29.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://30.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://31.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://32.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://33.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://34.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://35.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://36.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://37.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://38.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://39.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://40.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://41.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://42.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://43.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://44.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://45.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://46.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://47.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://48.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://49.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://50.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://51.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://52.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://53.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://54.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://55.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://56.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://57.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://58.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://59.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://60.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://61.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://62.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://63.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://64.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://65.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://66.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://67.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://68.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://69.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://70.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://71.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://72.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://73.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://74.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://75.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://76.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://77.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://78.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://79.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://80.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://81.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://82.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://83.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://84.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://85.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://86.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://87.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://88.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://89.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://90.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://91.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://92.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://93.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://94.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://95.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://96.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://97.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://98.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://99.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
- type: http
  urls: ["http://100.${domain}"]
  schedule: '@every 10s'
  timeout: 1s
